import { ReportsTableConfigProps } from './reportsModels';

export const ReportsTableConfig: ReportsTableConfigProps[] = [
  /*{
    key: 1,
    title: 'Ad Name',
    value: 'ad_name',
    checkbox: false,
  },*/
  {
    key: 2,
    title: 'Frequency',
    value: 'frequency',
    checkbox: true,
  },
  {
    key: 3,
    title: 'Impressions',
    value: 'impressions',
    checkbox: true,
  },
  {
    key: 4,
    title: 'Clicks',
    value: 'clicks',
    checkbox: true,
  },
  {
    key: 5,
    title: 'Reach',
    value: 'reach',
    checkbox: true,
  },
  {
    key: 6,
    title: 'Spend',
    value: 'spend',
    checkbox: true,
  },
  {
    key: 7,
    title: 'Start Date',
    value: 'date_start',
    checkbox: false,
  },
  {
    key: 8,
    title: 'Stop Date',
    value: 'date_stop',
    checkbox: false,
  },
  {
    key: 9,
    title: 'Buying Type',
    value: 'buying_type',
    checkbox: false,
  },
  {
    key: 10,
    title: 'Canvas Avg View Percent',
    value: 'canvas_avg_view_percent',
    checkbox: true,
  },
  {
    key: 11,
    title: 'Canvas Avg View Time',
    value: 'canvas_avg_view_time',
    checkbox: true,
  },
  {
    key: 12,
    title: 'Conversion Rate Ranking',
    value: 'conversion_rate_ranking',
    checkbox: false,
  },
  {
    key: 13,
    title: 'Engagement Rate Ranking',
    value: 'engagement_rate_ranking',
    checkbox: false,
  },
  {
    key: 14,
    title: 'Estimated Ad Recallers',
    value: 'estimated_ad_recallers',
    checkbox: true,
  },
  {
    key: 15,
    title: 'Instant Experience Clicks to Open',
    value: 'instant_experience_clicks_to_open',
    checkbox: true,
  },
  {
    key: 16,
    title: 'Objective',
    value: 'objective',
    checkbox: false,
  },
  {
    key: 17,
    title: 'Optimization Goal',
    value: 'optimization_goal',
    checkbox: false,
  },
  {
    key: 18,
    title: 'Quality Ranking',
    value: 'quality_ranking',
    checkbox: false,
  },
  {
    key: 19,
    title: 'Social Spend',
    value: 'social_spend',
    checkbox: true,
  },
  {
    key: 20,
    title: 'Video Watched 3s Percent',
    value: 'video_watched_3_s_percent',
    checkbox: true,
  },
  {
    key: 21,
    title: 'Video Watched 15s Percent',
    value: 'video_watched_15_s_percent',
    checkbox: true,
  },
  {
    key: 22,
    title: 'Video Watched 30s Percent',
    value: 'video_watched_30_s_percent',
    checkbox: true,
  },
  {
    key: 23,
    title: 'Video Watched 0s Count',
    value: 'video_watched_0_s_count',
    checkbox: true,
  },
  {
    key: 24,
    title: 'Video Watched 3s Count',
    value: 'video_watched_3_s_count',
    checkbox: true,
  },
  {
    key: 25,
    title: 'Video Watched 15s Count',
    value: 'video_watched_15_s_count',
    checkbox: true,
  },
  {
    key: 26,
    title: 'Video Watched 30s Count',
    value: 'video_watched_30_s_count',
    checkbox: true,
  },
  {
    key: 27,
    title: 'Video Watched 25% Play Count',
    value: 'video_watched_25_p_count',
    checkbox: true,
  },
  {
    key: 28,
    title: 'Video Watched 50% Play Count',
    value: 'video_watched_50_p_count',
    checkbox: true,
  },
  {
    key: 29,
    title: 'Video Watched 75% Play Count',
    value: 'video_watched_75_p_count',
    checkbox: true,
  },
  {
    key: 30,
    title: 'Video Watched 95% Play Count',
    value: 'video_watched_95_p_count',
    checkbox: true,
  },
  {
    key: 31,
    title: 'Video Watched 100% Play Count',
    value: 'video_watched_100_p_count',
    checkbox: true,
  },
  {
    key: 32,
    title: 'First Frame Retention',
    value: 'first_frame_retention',
    checkbox: true,
  },
  {
    key: 33,
    title: 'Video Watched 25% Play',
    value: 'video_watched_25_p',
    checkbox: true,
  },
  {
    key: 34,
    title: 'Video Watched 50% Play',
    value: 'video_watched_50_p',
    checkbox: true,
  },
  {
    key: 35,
    title: 'Video Watched 75% Play',
    value: 'video_watched_75_p',
    checkbox: true,
  },
  {
    key: 36,
    title: 'Video Watched 95% Play',
    value: 'video_watched_95_p',
    checkbox: true,
  },
  {
    key: 37,
    title: 'Video Watched 100% Play',
    value: 'video_watched_100_p',
    checkbox: true,
  },
  {
    key: 38,
    title: 'Capture Attention',
    value: 'capture_attention',
    checkbox: true,
  },
  {
    key: 39,
    title: 'Hold Attention',
    value: 'hold_attention',
    checkbox: true,
  },
  {
    key: 40,
    title: 'Capture Attention Rate',
    value: 'capture_attention_rate',
    checkbox: true,
  },
  {
    key: 41,
    title: 'Hold Attention Rate',
    value: 'hold_attention_rate',
    checkbox: true,
  },
  {
    key: 42,
    title: 'Engagement',
    value: 'engagment',
    checkbox: true,
  },
  {
    key: 43,
    title: 'Engagement Percent',
    value: 'engagment_percent',
    checkbox: true,
  },
  {
    key: 44,
    title: 'Click to Website',
    value: 'click_to_website',
    checkbox: true,
  },
  {
    key: 45,
    title: 'Website CTR',
    value: 'web_site_ctr',
    checkbox: true,
  },
  {
    key: 46,
    title: 'Link Clicks',
    value: 'link_clicks',
    checkbox: true,
  },
  {
    key: 47,
    title: 'CPC Outbound Link Click',
    value: 'cpc_outbound_link_click',
    checkbox: true,
  },
  {
    key: 48,
    title: 'Clicks All',
    value: 'clicks_all',
    checkbox: true,
  },
  {
    key: 49,
    title: 'IPM',
    value: 'ipm',
    checkbox: true,
  },
  {
    key: 50,
    title: 'CPA',
    value: 'cpa',
    checkbox: true,
  },
  {
    key: 51,
    title: 'CPC Link Click',
    value: 'cpc_link_click',
    checkbox: true,
  },
  {
    key: 52,
    title: 'CPM All',
    value: 'cpm_all',
    checkbox: true,
  },
  {
    key: 53,
    title: 'CPA Video View',
    value: 'cpa_video_view',
    checkbox: true,
  },
  {
    key: 54,
    title: 'CPA Link Click',
    value: 'cpa_link_click',
    checkbox: true,
  },
  {
    key: 55,
    title: 'Cost per 3s Plays',
    value: 'cost_per_3_s_plays',
    checkbox: true,
  },
  {
    key: 56,
    title: 'Video Retention 100% 3s',
    value: 'video_retention_100p_3s',
    checkbox: true,
  },
  {
    key: 57,
    title: 'Video Retention 15s 3s',
    value: 'video_retention_15s_3s',
    checkbox: true,
  },
  {
    key: 58,
    title: 'Thruplay',
    value: 'thruplay',
    checkbox: true,
  },
  {
    key: 59,
    title: 'Thruplay CTR',
    value: 'thruplay_ctr',
    checkbox: true,
  },
  {
    key: 60,
    title: 'CTR All',
    value: 'ctr_all',
    checkbox: true,
  },
  {
    key: 61,
    title: 'Thumbstop',
    value: 'thumbstop',
    checkbox: true,
  },
  {
    key: 62,
    title: 'Thumbstop Clickrate',
    value: 'thumbstop_clickrate',
    checkbox: true,
  },
  {
    key: 63,
    title: 'Add to Cart',
    value: 'atc',
    checkbox: true,
  },
];
