import { TemporaryAdsetsDataProps } from './reportsModels';

const TemporaryAdsetsData: TemporaryAdsetsDataProps[] = [
  {
    facebookAccount: {
      facebookId: '1496187210941809',
      firstName: 'Maks',
      lastName: 'Kochetkov',
    },
    adSets: [
      {
        adSet: {
          name: 'Публикация: «Амортизатор Monroe Амортизатор Sensa-Trac газовый...»',
          account_id: '111944016032809',
          campaign_id: '23842591500440110',
          id: '23842591500530110',
        },
        insights: {
          frequency: 10,
          impressions: 20,
          clicks: 30,
          reach: 10,
          spend: 0,
          date_start: 2021,
          date_stop: 2024,
          buying_type: 'AUCTION',
          canvas_avg_view_percent: 40,
          canvas_avg_view_time: 50,
          conversion_rate_ranking: 'UNKNOWN',
          engagement_rate_ranking: 'UNKNOWN',
          estimated_ad_recallers: 60,
          instant_experience_clicks_to_open: 70,
          objective: 'POST_ENGAGEMENT',
          optimization_goal: 'POST_ENGAGEMENT',
          quality_ranking: 'UNKNOWN',
          social_spend: 30,
          ad_name:
            'Публикация: «Амортизатор Monroe Амортизатор Sensa-Trac газовый...»',
          ad_id: 23842591500540110,
          adset_id: 23842591500530110,
          adset_name:
            'Публикация: «Амортизатор Monroe Амортизатор Sensa-Trac газовый...»',
          campaign_name:
            'Публикация: «Амортизатор Monroe Амортизатор Sensa-Trac газовый...»',
          campaign_id: 23842591500440110,
          video_watched_3_s_percent: 80,
          video_watched_15_s_percent: 90,
          video_watched_30_s_percent: 20,
          video_watched_0_s_count: 30,
          video_watched_3_s_count: 40,
          video_watched_15_s_count: 40,
          video_watched_30_s_count: 40,
          video_watched_25_p_count: 15,
          video_watched_50_p_count: 20,
          video_watched_75_p_count: 25,
          video_watched_95_p_count: 40,
          video_watched_100_p_count: 30,
          first_frame_retention: 50,
          video_watched_25_p: 60,
          video_watched_50_p: 70,
          video_watched_75_p: 80,
          video_watched_95_p: 70,
          video_watched_100_p: 70,
          capture_attention: 60,
          hold_attention: 50,
          capture_attention_rate: 50,
          hold_attention_rate: 50,
          engagment: 60,
          engagment_percent: 60,
          click_to_website: 70,
          web_site_ctr: 70,
          link_clicks: 80,
          cpc_outbound_link_click: 90,
          clicks_all: 80,
          ipm: 40,
          cpa: 40,
          cpc_link_click: 30,
          cpm_all: 20,
          cpa_video_view: 10,
          cpa_link_click: 30,
          cost_per_3_s_plays: 30,
          video_retention_100p_3s: 40,
          video_retention_15s_3s: 50,
          thruplay: null,
          thruplay_ctr: 60,
          ctr_all: null,
          thumbstop: 0,
          thumbstop_clickrate: 0,
          atc: 0,
          video_play_curve_actions: [],
        },
        ads: [
          {
            name: 'Публикация: «Амортизатор Monroe Амортизатор Sensa-Trac газовый...»',
            id: '23842591500540110',
          },
        ],
      },
    ],
  },
  {
    facebookAccount: {
      facebookId: '1546855882562934',
      firstName: 'John',
      lastName: 'Doe',
    },
    adSets: [
      {
        adSet: {
          name: 'Публикация: «Амортизатор Monroe Амортизатор Sensa-Trac газовый...»',
          account_id: '111944016032809',
          campaign_id: '23842591500440110',
          id: '23842591500530110',
        },
        insights: {
          frequency: 0,
          impressions: 0,
          clicks: 0,
          reach: 0,
          spend: 0,
          date_start: 2021,
          date_stop: 2024,
          buying_type: 'AUCTION',
          canvas_avg_view_percent: 0,
          canvas_avg_view_time: 0,
          conversion_rate_ranking: 'UNKNOWN',
          engagement_rate_ranking: 'UNKNOWN',
          estimated_ad_recallers: 0,
          instant_experience_clicks_to_open: 0,
          objective: 'POST_ENGAGEMENT',
          optimization_goal: 'POST_ENGAGEMENT',
          quality_ranking: 'UNKNOWN',
          social_spend: 0,
          ad_name:
            'Публикация: «Амортизатор Monroe Амортизатор Sensa-Trac газовый...»',
          ad_id: 23842591500540110,
          adset_id: 23842591500530110,
          adset_name:
            'Публикация: «Амортизатор Monroe Амортизатор Sensa-Trac газовый...»',
          campaign_name:
            'Публикация: «Амортизатор Monroe Амортизатор Sensa-Trac газовый...»',
          campaign_id: 23842591500440110,
          video_watched_3_s_percent: 0,
          video_watched_15_s_percent: 0,
          video_watched_30_s_percent: 0,
          video_watched_0_s_count: 0,
          video_watched_3_s_count: 0,
          video_watched_15_s_count: 0,
          video_watched_30_s_count: 0,
          video_watched_25_p_count: 0,
          video_watched_50_p_count: 0,
          video_watched_75_p_count: 0,
          video_watched_95_p_count: 0,
          video_watched_100_p_count: 0,
          first_frame_retention: 0,
          video_watched_25_p: 0,
          video_watched_50_p: 0,
          video_watched_75_p: 0,
          video_watched_95_p: 0,
          video_watched_100_p: 0,
          capture_attention: 0,
          hold_attention: 0,
          capture_attention_rate: 0,
          hold_attention_rate: 0,
          engagment: 0,
          engagment_percent: 0,
          click_to_website: 0,
          web_site_ctr: 0,
          link_clicks: 0,
          cpc_outbound_link_click: 0,
          clicks_all: 0,
          ipm: 0,
          cpa: 0,
          cpc_link_click: 0,
          cpm_all: 0,
          cpa_video_view: 0,
          cpa_link_click: 0,
          cost_per_3_s_plays: 0,
          video_retention_100p_3s: 0,
          video_retention_15s_3s: 0,
          thruplay: null,
          thruplay_ctr: 0,
          ctr_all: null,
          thumbstop: 0,
          thumbstop_clickrate: 0,
          atc: 0,
          video_play_curve_actions: [],
        },
        ads: [
          {
            name: 'Публикация: «Амортизатор Monroe Амортизатор Sensa-Trac газовый...»',
            id: '23842591500540110',
          },
        ],
      },
    ],
  },
  {
    facebookAccount: {
      facebookId: '1546855882562934',
      firstName: 'Jane',
      lastName: 'Smith',
    },
    adSets: [
      {
        adSet: {
          name: 'Публикация: «Амортизатор Monroe Амортизатор Sensa-Trac газовый...»',
          account_id: '111944016032809',
          campaign_id: '23842591500440110',
          id: '23842591500530110',
        },
        insights: {
          frequency: 0,
          impressions: 0,
          clicks: 0,
          reach: 0,
          spend: 0,
          date_start: 2021,
          date_stop: 2024,
          buying_type: 'AUCTION',
          canvas_avg_view_percent: 0,
          canvas_avg_view_time: 0,
          conversion_rate_ranking: 'UNKNOWN',
          engagement_rate_ranking: 'UNKNOWN',
          estimated_ad_recallers: 0,
          instant_experience_clicks_to_open: 0,
          objective: 'POST_ENGAGEMENT',
          optimization_goal: 'POST_ENGAGEMENT',
          quality_ranking: 'UNKNOWN',
          social_spend: 0,
          ad_name:
            'Публикация: «Амортизатор Monroe Амортизатор Sensa-Trac газовый...»',
          ad_id: 23842591500540110,
          adset_id: 23842591500530110,
          adset_name:
            'Публикация: «Амортизатор Monroe Амортизатор Sensa-Trac газовый...»',
          campaign_name:
            'Публикация: «Амортизатор Monroe Амортизатор Sensa-Trac газовый...»',
          campaign_id: 23842591500440110,
          video_watched_3_s_percent: 0,
          video_watched_15_s_percent: 0,
          video_watched_30_s_percent: 0,
          video_watched_0_s_count: 0,
          video_watched_3_s_count: 0,
          video_watched_15_s_count: 0,
          video_watched_30_s_count: 0,
          video_watched_25_p_count: 0,
          video_watched_50_p_count: 0,
          video_watched_75_p_count: 0,
          video_watched_95_p_count: 0,
          video_watched_100_p_count: 0,
          first_frame_retention: 0,
          video_watched_25_p: 0,
          video_watched_50_p: 0,
          video_watched_75_p: 0,
          video_watched_95_p: 0,
          video_watched_100_p: 0,
          capture_attention: 0,
          hold_attention: 0,
          capture_attention_rate: 0,
          hold_attention_rate: 0,
          engagment: 0,
          engagment_percent: 0,
          click_to_website: 0,
          web_site_ctr: 0,
          link_clicks: 0,
          cpc_outbound_link_click: 0,
          clicks_all: 0,
          ipm: 0,
          cpa: 0,
          cpc_link_click: 0,
          cpm_all: 0,
          cpa_video_view: 0,
          cpa_link_click: 0,
          cost_per_3_s_plays: 0,
          video_retention_100p_3s: 0,
          video_retention_15s_3s: 0,
          thruplay: null,
          thruplay_ctr: 0,
          ctr_all: null,
          thumbstop: 0,
          thumbstop_clickrate: 0,
          atc: 0,
          video_play_curve_actions: [],
        },
        ads: [
          {
            name: 'Публикация: «Амортизатор Monroe Амортизатор Sensa-Trac газовый...»',
            id: '23842591500540110',
          },
        ],
      },
    ],
  },
  {
    facebookAccount: {
      facebookId: '1546855882562934',
      firstName: 'Michael',
      lastName: 'Johnson',
    },
    adSets: [
      {
        adSet: {
          name: 'Публикация: «Амортизатор Monroe Амортизатор Sensa-Trac газовый...»',
          account_id: '111944016032809',
          campaign_id: '23842591500440110',
          id: '23842591500530110',
        },
        insights: {
          frequency: 0,
          impressions: 0,
          clicks: 0,
          reach: 0,
          spend: 0,
          date_start: 2021,
          date_stop: 2024,
          buying_type: 'AUCTION',
          canvas_avg_view_percent: 0,
          canvas_avg_view_time: 0,
          conversion_rate_ranking: 'UNKNOWN',
          engagement_rate_ranking: 'UNKNOWN',
          estimated_ad_recallers: 0,
          instant_experience_clicks_to_open: 0,
          objective: 'POST_ENGAGEMENT',
          optimization_goal: 'POST_ENGAGEMENT',
          quality_ranking: 'UNKNOWN',
          social_spend: 0,
          ad_name:
            'Публикация: «Амортизатор Monroe Амортизатор Sensa-Trac газовый...»',
          ad_id: 23842591500540110,
          adset_id: 23842591500530110,
          adset_name:
            'Публикация: «Амортизатор Monroe Амортизатор Sensa-Trac газовый...»',
          campaign_name:
            'Публикация: «Амортизатор Monroe Амортизатор Sensa-Trac газовый...»',
          campaign_id: 23842591500440110,
          video_watched_3_s_percent: 0,
          video_watched_15_s_percent: 0,
          video_watched_30_s_percent: 0,
          video_watched_0_s_count: 0,
          video_watched_3_s_count: 0,
          video_watched_15_s_count: 0,
          video_watched_30_s_count: 0,
          video_watched_25_p_count: 0,
          video_watched_50_p_count: 0,
          video_watched_75_p_count: 0,
          video_watched_95_p_count: 0,
          video_watched_100_p_count: 0,
          first_frame_retention: 0,
          video_watched_25_p: 0,
          video_watched_50_p: 0,
          video_watched_75_p: 0,
          video_watched_95_p: 0,
          video_watched_100_p: 0,
          capture_attention: 0,
          hold_attention: 0,
          capture_attention_rate: 0,
          hold_attention_rate: 0,
          engagment: 0,
          engagment_percent: 0,
          click_to_website: 0,
          web_site_ctr: 0,
          link_clicks: 0,
          cpc_outbound_link_click: 0,
          clicks_all: 0,
          ipm: 0,
          cpa: 0,
          cpc_link_click: 0,
          cpm_all: 0,
          cpa_video_view: 0,
          cpa_link_click: 0,
          cost_per_3_s_plays: 0,
          video_retention_100p_3s: 0,
          video_retention_15s_3s: 0,
          thruplay: null,
          thruplay_ctr: 0,
          ctr_all: null,
          thumbstop: 0,
          thumbstop_clickrate: 0,
          atc: 0,
          video_play_curve_actions: [],
        },
        ads: [
          {
            name: 'Публикация: «Амортизатор Monroe Амортизатор Sensa-Trac газовый...»',
            id: '23842591500540110',
          },
        ],
      },
    ],
  },
  {
    facebookAccount: {
      facebookId: '1546855882562934',
      firstName: 'Emily',
      lastName: 'Williams',
    },
    adSets: [
      {
        adSet: {
          name: 'Публикация: «Амортизатор Monroe Амортизатор Sensa-Trac газовый...»',
          account_id: '111944016032809',
          campaign_id: '23842591500440110',
          id: '23842591500530110',
        },
        insights: {
          frequency: 0,
          impressions: 0,
          clicks: 0,
          reach: 0,
          spend: 0,
          date_start: 2021,
          date_stop: 2024,
          buying_type: 'AUCTION',
          canvas_avg_view_percent: 0,
          canvas_avg_view_time: 0,
          conversion_rate_ranking: 'UNKNOWN',
          engagement_rate_ranking: 'UNKNOWN',
          estimated_ad_recallers: 0,
          instant_experience_clicks_to_open: 0,
          objective: 'POST_ENGAGEMENT',
          optimization_goal: 'POST_ENGAGEMENT',
          quality_ranking: 'UNKNOWN',
          social_spend: 0,
          ad_name:
            'Публикация: «Амортизатор Monroe Амортизатор Sensa-Trac газовый...»',
          ad_id: 23842591500540110,
          adset_id: 23842591500530110,
          adset_name:
            'Публикация: «Амортизатор Monroe Амортизатор Sensa-Trac газовый...»',
          campaign_name:
            'Публикация: «Амортизатор Monroe Амортизатор Sensa-Trac газовый...»',
          campaign_id: 23842591500440110,
          video_watched_3_s_percent: 0,
          video_watched_15_s_percent: 0,
          video_watched_30_s_percent: 0,
          video_watched_0_s_count: 0,
          video_watched_3_s_count: 0,
          video_watched_15_s_count: 0,
          video_watched_30_s_count: 0,
          video_watched_25_p_count: 0,
          video_watched_50_p_count: 0,
          video_watched_75_p_count: 0,
          video_watched_95_p_count: 0,
          video_watched_100_p_count: 0,
          first_frame_retention: 0,
          video_watched_25_p: 0,
          video_watched_50_p: 0,
          video_watched_75_p: 0,
          video_watched_95_p: 0,
          video_watched_100_p: 0,
          capture_attention: 0,
          hold_attention: 0,
          capture_attention_rate: 0,
          hold_attention_rate: 0,
          engagment: 0,
          engagment_percent: 0,
          click_to_website: 0,
          web_site_ctr: 0,
          link_clicks: 0,
          cpc_outbound_link_click: 0,
          clicks_all: 0,
          ipm: 0,
          cpa: 0,
          cpc_link_click: 0,
          cpm_all: 0,
          cpa_video_view: 0,
          cpa_link_click: 0,
          cost_per_3_s_plays: 0,
          video_retention_100p_3s: 0,
          video_retention_15s_3s: 0,
          thruplay: null,
          thruplay_ctr: 0,
          ctr_all: null,
          thumbstop: 0,
          thumbstop_clickrate: 0,
          atc: 0,
          video_play_curve_actions: [],
        },
        ads: [
          {
            name: 'Публикация: «Амортизатор Monroe Амортизатор Sensa-Trac газовый...»',
            id: '23842591500540110',
          },
        ],
      },
    ],
  },
  {
    facebookAccount: {
      facebookId: '1546855882562934',
      firstName: 'David',
      lastName: 'Brown',
    },
    adSets: [
      {
        adSet: {
          name: 'Публикация: «Амортизатор Monroe Амортизатор Sensa-Trac газовый...»',
          account_id: '111944016032809',
          campaign_id: '23842591500440110',
          id: '23842591500530110',
        },
        insights: {
          frequency: 0,
          impressions: 0,
          clicks: 0,
          reach: 0,
          spend: 0,
          date_start: 2021,
          date_stop: 2024,
          buying_type: 'AUCTION',
          canvas_avg_view_percent: 0,
          canvas_avg_view_time: 0,
          conversion_rate_ranking: 'UNKNOWN',
          engagement_rate_ranking: 'UNKNOWN',
          estimated_ad_recallers: 0,
          instant_experience_clicks_to_open: 0,
          objective: 'POST_ENGAGEMENT',
          optimization_goal: 'POST_ENGAGEMENT',
          quality_ranking: 'UNKNOWN',
          social_spend: 0,
          ad_name:
            'Публикация: «Амортизатор Monroe Амортизатор Sensa-Trac газовый...»',
          ad_id: 23842591500540110,
          adset_id: 23842591500530110,
          adset_name:
            'Публикация: «Амортизатор Monroe Амортизатор Sensa-Trac газовый...»',
          campaign_name:
            'Публикация: «Амортизатор Monroe Амортизатор Sensa-Trac газовый...»',
          campaign_id: 23842591500440110,
          video_watched_3_s_percent: 0,
          video_watched_15_s_percent: 0,
          video_watched_30_s_percent: 0,
          video_watched_0_s_count: 0,
          video_watched_3_s_count: 0,
          video_watched_15_s_count: 0,
          video_watched_30_s_count: 0,
          video_watched_25_p_count: 0,
          video_watched_50_p_count: 0,
          video_watched_75_p_count: 0,
          video_watched_95_p_count: 0,
          video_watched_100_p_count: 0,
          first_frame_retention: 0,
          video_watched_25_p: 0,
          video_watched_50_p: 0,
          video_watched_75_p: 0,
          video_watched_95_p: 0,
          video_watched_100_p: 0,
          capture_attention: 0,
          hold_attention: 0,
          capture_attention_rate: 0,
          hold_attention_rate: 0,
          engagment: 0,
          engagment_percent: 0,
          click_to_website: 0,
          web_site_ctr: 0,
          link_clicks: 0,
          cpc_outbound_link_click: 0,
          clicks_all: 0,
          ipm: 0,
          cpa: 0,
          cpc_link_click: 0,
          cpm_all: 0,
          cpa_video_view: 0,
          cpa_link_click: 0,
          cost_per_3_s_plays: 0,
          video_retention_100p_3s: 0,
          video_retention_15s_3s: 0,
          thruplay: null,
          thruplay_ctr: 0,
          ctr_all: null,
          thumbstop: 0,
          thumbstop_clickrate: 0,
          atc: 0,
          video_play_curve_actions: [],
        },
        ads: [
          {
            name: 'Публикация: «Амортизатор Monroe Амортизатор Sensa-Trac газовый...»',
            id: '23842591500540110',
          },
        ],
      },
    ],
  },
  {
    facebookAccount: {
      facebookId: '1546855882562934',
      firstName: 'Sarah',
      lastName: 'Davis',
    },
    adSets: [
      {
        adSet: {
          name: 'Публикация: «Амортизатор Monroe Амортизатор Sensa-Trac газовый...»',
          account_id: '111944016032809',
          campaign_id: '23842591500440110',
          id: '23842591500530110',
        },
        insights: {
          frequency: 0,
          impressions: 0,
          clicks: 0,
          reach: 0,
          spend: 0,
          date_start: 2021,
          date_stop: 2024,
          buying_type: 'AUCTION',
          canvas_avg_view_percent: 0,
          canvas_avg_view_time: 0,
          conversion_rate_ranking: 'UNKNOWN',
          engagement_rate_ranking: 'UNKNOWN',
          estimated_ad_recallers: 0,
          instant_experience_clicks_to_open: 0,
          objective: 'POST_ENGAGEMENT',
          optimization_goal: 'POST_ENGAGEMENT',
          quality_ranking: 'UNKNOWN',
          social_spend: 0,
          ad_name:
            'Публикация: «Амортизатор Monroe Амортизатор Sensa-Trac газовый...»',
          ad_id: 23842591500540110,
          adset_id: 23842591500530110,
          adset_name:
            'Публикация: «Амортизатор Monroe Амортизатор Sensa-Trac газовый...»',
          campaign_name:
            'Публикация: «Амортизатор Monroe Амортизатор Sensa-Trac газовый...»',
          campaign_id: 23842591500440110,
          video_watched_3_s_percent: 0,
          video_watched_15_s_percent: 0,
          video_watched_30_s_percent: 0,
          video_watched_0_s_count: 0,
          video_watched_3_s_count: 0,
          video_watched_15_s_count: 0,
          video_watched_30_s_count: 0,
          video_watched_25_p_count: 0,
          video_watched_50_p_count: 0,
          video_watched_75_p_count: 0,
          video_watched_95_p_count: 0,
          video_watched_100_p_count: 0,
          first_frame_retention: 0,
          video_watched_25_p: 0,
          video_watched_50_p: 0,
          video_watched_75_p: 0,
          video_watched_95_p: 0,
          video_watched_100_p: 0,
          capture_attention: 0,
          hold_attention: 0,
          capture_attention_rate: 0,
          hold_attention_rate: 0,
          engagment: 0,
          engagment_percent: 0,
          click_to_website: 0,
          web_site_ctr: 0,
          link_clicks: 0,
          cpc_outbound_link_click: 0,
          clicks_all: 0,
          ipm: 0,
          cpa: 0,
          cpc_link_click: 0,
          cpm_all: 0,
          cpa_video_view: 0,
          cpa_link_click: 0,
          cost_per_3_s_plays: 0,
          video_retention_100p_3s: 0,
          video_retention_15s_3s: 0,
          thruplay: null,
          thruplay_ctr: 0,
          ctr_all: null,
          thumbstop: 0,
          thumbstop_clickrate: 0,
          atc: 0,
          video_play_curve_actions: [],
        },
        ads: [
          {
            name: 'Публикация: «Амортизатор Monroe Амортизатор Sensa-Trac газовый...»',
            id: '23842591500540110',
          },
        ],
      },
    ],
  },
  {
    facebookAccount: {
      facebookId: '1546855882562934',
      firstName: 'Christopher',
      lastName: 'Miller',
    },
    adSets: [
      {
        adSet: {
          name: 'Публикация: «Амортизатор Monroe Амортизатор Sensa-Trac газовый...»',
          account_id: '111944016032809',
          campaign_id: '23842591500440110',
          id: '23842591500530110',
        },
        insights: {
          frequency: 0,
          impressions: 0,
          clicks: 0,
          reach: 0,
          spend: 0,
          date_start: 2021,
          date_stop: 2024,
          buying_type: 'AUCTION',
          canvas_avg_view_percent: 0,
          canvas_avg_view_time: 0,
          conversion_rate_ranking: 'UNKNOWN',
          engagement_rate_ranking: 'UNKNOWN',
          estimated_ad_recallers: 0,
          instant_experience_clicks_to_open: 0,
          objective: 'POST_ENGAGEMENT',
          optimization_goal: 'POST_ENGAGEMENT',
          quality_ranking: 'UNKNOWN',
          social_spend: 0,
          ad_name:
            'Публикация: «Амортизатор Monroe Амортизатор Sensa-Trac газовый...»',
          ad_id: 23842591500540110,
          adset_id: 23842591500530110,
          adset_name:
            'Публикация: «Амортизатор Monroe Амортизатор Sensa-Trac газовый...»',
          campaign_name:
            'Публикация: «Амортизатор Monroe Амортизатор Sensa-Trac газовый...»',
          campaign_id: 23842591500440110,
          video_watched_3_s_percent: 0,
          video_watched_15_s_percent: 0,
          video_watched_30_s_percent: 0,
          video_watched_0_s_count: 0,
          video_watched_3_s_count: 0,
          video_watched_15_s_count: 0,
          video_watched_30_s_count: 0,
          video_watched_25_p_count: 0,
          video_watched_50_p_count: 0,
          video_watched_75_p_count: 0,
          video_watched_95_p_count: 0,
          video_watched_100_p_count: 0,
          first_frame_retention: 0,
          video_watched_25_p: 0,
          video_watched_50_p: 0,
          video_watched_75_p: 0,
          video_watched_95_p: 0,
          video_watched_100_p: 0,
          capture_attention: 0,
          hold_attention: 0,
          capture_attention_rate: 0,
          hold_attention_rate: 0,
          engagment: 0,
          engagment_percent: 0,
          click_to_website: 0,
          web_site_ctr: 0,
          link_clicks: 0,
          cpc_outbound_link_click: 0,
          clicks_all: 0,
          ipm: 0,
          cpa: 0,
          cpc_link_click: 0,
          cpm_all: 0,
          cpa_video_view: 0,
          cpa_link_click: 0,
          cost_per_3_s_plays: 0,
          video_retention_100p_3s: 0,
          video_retention_15s_3s: 0,
          thruplay: null,
          thruplay_ctr: 0,
          ctr_all: null,
          thumbstop: 0,
          thumbstop_clickrate: 0,
          atc: 0,
          video_play_curve_actions: [],
        },
        ads: [
          {
            name: 'Публикация: «Амортизатор Monroe Амортизатор Sensa-Trac газовый...»',
            id: '23842591500540110',
          },
        ],
      },
    ],
  },
  {
    facebookAccount: {
      facebookId: '1546855882562934',
      firstName: 'Jessica',
      lastName: 'Wilson',
    },
    adSets: [
      {
        adSet: {
          name: 'Публикация: «Амортизатор Monroe Амортизатор Sensa-Trac газовый...»',
          account_id: '111944016032809',
          campaign_id: '23842591500440110',
          id: '23842591500530110',
        },
        insights: {
          frequency: 0,
          impressions: 0,
          clicks: 0,
          reach: 0,
          spend: 0,
          date_start: 2021,
          date_stop: 2024,
          buying_type: 'AUCTION',
          canvas_avg_view_percent: 0,
          canvas_avg_view_time: 0,
          conversion_rate_ranking: 'UNKNOWN',
          engagement_rate_ranking: 'UNKNOWN',
          estimated_ad_recallers: 0,
          instant_experience_clicks_to_open: 0,
          objective: 'POST_ENGAGEMENT',
          optimization_goal: 'POST_ENGAGEMENT',
          quality_ranking: 'UNKNOWN',
          social_spend: 0,
          ad_name:
            'Публикация: «Амортизатор Monroe Амортизатор Sensa-Trac газовый...»',
          ad_id: 23842591500540110,
          adset_id: 23842591500530110,
          adset_name:
            'Публикация: «Амортизатор Monroe Амортизатор Sensa-Trac газовый...»',
          campaign_name:
            'Публикация: «Амортизатор Monroe Амортизатор Sensa-Trac газовый...»',
          campaign_id: 23842591500440110,
          video_watched_3_s_percent: 0,
          video_watched_15_s_percent: 0,
          video_watched_30_s_percent: 0,
          video_watched_0_s_count: 0,
          video_watched_3_s_count: 0,
          video_watched_15_s_count: 0,
          video_watched_30_s_count: 0,
          video_watched_25_p_count: 0,
          video_watched_50_p_count: 0,
          video_watched_75_p_count: 0,
          video_watched_95_p_count: 0,
          video_watched_100_p_count: 0,
          first_frame_retention: 0,
          video_watched_25_p: 0,
          video_watched_50_p: 0,
          video_watched_75_p: 0,
          video_watched_95_p: 0,
          video_watched_100_p: 0,
          capture_attention: 0,
          hold_attention: 0,
          capture_attention_rate: 0,
          hold_attention_rate: 0,
          engagment: 0,
          engagment_percent: 0,
          click_to_website: 0,
          web_site_ctr: 0,
          link_clicks: 0,
          cpc_outbound_link_click: 0,
          clicks_all: 0,
          ipm: 0,
          cpa: 0,
          cpc_link_click: 0,
          cpm_all: 0,
          cpa_video_view: 0,
          cpa_link_click: 0,
          cost_per_3_s_plays: 0,
          video_retention_100p_3s: 0,
          video_retention_15s_3s: 0,
          thruplay: null,
          thruplay_ctr: 0,
          ctr_all: null,
          thumbstop: 0,
          thumbstop_clickrate: 0,
          atc: 0,
          video_play_curve_actions: [],
        },
        ads: [
          {
            name: 'Публикация: «Амортизатор Monroe Амортизатор Sensa-Trac газовый...»',
            id: '23842591500540110',
          },
        ],
      },
    ],
  },
  {
    facebookAccount: {
      facebookId: '1546855882562934',
      firstName: 'Matthew',
      lastName: 'Moore',
    },
    adSets: [
      {
        adSet: {
          name: 'Публикация: «Амортизатор Monroe Амортизатор Sensa-Trac газовый...»',
          account_id: '111944016032809',
          campaign_id: '23842591500440110',
          id: '23842591500530110',
        },
        insights: {
          frequency: 0,
          impressions: 0,
          clicks: 0,
          reach: 0,
          spend: 0,
          date_start: 2021,
          date_stop: 2024,
          buying_type: 'AUCTION',
          canvas_avg_view_percent: 0,
          canvas_avg_view_time: 0,
          conversion_rate_ranking: 'UNKNOWN',
          engagement_rate_ranking: 'UNKNOWN',
          estimated_ad_recallers: 0,
          instant_experience_clicks_to_open: 0,
          objective: 'POST_ENGAGEMENT',
          optimization_goal: 'POST_ENGAGEMENT',
          quality_ranking: 'UNKNOWN',
          social_spend: 0,
          ad_name:
            'Публикация: «Амортизатор Monroe Амортизатор Sensa-Trac газовый...»',
          ad_id: 23842591500540110,
          adset_id: 23842591500530110,
          adset_name:
            'Публикация: «Амортизатор Monroe Амортизатор Sensa-Trac газовый...»',
          campaign_name:
            'Публикация: «Амортизатор Monroe Амортизатор Sensa-Trac газовый...»',
          campaign_id: 23842591500440110,
          video_watched_3_s_percent: 0,
          video_watched_15_s_percent: 0,
          video_watched_30_s_percent: 0,
          video_watched_0_s_count: 0,
          video_watched_3_s_count: 0,
          video_watched_15_s_count: 0,
          video_watched_30_s_count: 0,
          video_watched_25_p_count: 0,
          video_watched_50_p_count: 0,
          video_watched_75_p_count: 0,
          video_watched_95_p_count: 0,
          video_watched_100_p_count: 0,
          first_frame_retention: 0,
          video_watched_25_p: 0,
          video_watched_50_p: 0,
          video_watched_75_p: 0,
          video_watched_95_p: 0,
          video_watched_100_p: 0,
          capture_attention: 0,
          hold_attention: 0,
          capture_attention_rate: 0,
          hold_attention_rate: 0,
          engagment: 0,
          engagment_percent: 0,
          click_to_website: 0,
          web_site_ctr: 0,
          link_clicks: 0,
          cpc_outbound_link_click: 0,
          clicks_all: 0,
          ipm: 0,
          cpa: 0,
          cpc_link_click: 0,
          cpm_all: 0,
          cpa_video_view: 0,
          cpa_link_click: 0,
          cost_per_3_s_plays: 0,
          video_retention_100p_3s: 0,
          video_retention_15s_3s: 0,
          thruplay: null,
          thruplay_ctr: 0,
          ctr_all: null,
          thumbstop: 0,
          thumbstop_clickrate: 0,
          atc: 0,
          video_play_curve_actions: [],
        },
        ads: [
          {
            name: 'Публикация: «Амортизатор Monroe Амортизатор Sensa-Trac газовый...»',
            id: '23842591500540110',
          },
        ],
      },
    ],
  },
  {
    facebookAccount: {
      facebookId: '1546855882562934',
      firstName: 'Ashley',
      lastName: 'Taylor',
    },
    adSets: [
      {
        adSet: {
          name: 'Публикация: «Амортизатор Monroe Амортизатор Sensa-Trac газовый...»',
          account_id: '111944016032809',
          campaign_id: '23842591500440110',
          id: '23842591500530110',
        },
        insights: {
          frequency: 0,
          impressions: 0,
          clicks: 0,
          reach: 0,
          spend: 0,
          date_start: 2021,
          date_stop: 2024,
          buying_type: 'AUCTION',
          canvas_avg_view_percent: 0,
          canvas_avg_view_time: 0,
          conversion_rate_ranking: 'UNKNOWN',
          engagement_rate_ranking: 'UNKNOWN',
          estimated_ad_recallers: 0,
          instant_experience_clicks_to_open: 0,
          objective: 'POST_ENGAGEMENT',
          optimization_goal: 'POST_ENGAGEMENT',
          quality_ranking: 'UNKNOWN',
          social_spend: 0,
          ad_name:
            'Публикация: «Амортизатор Monroe Амортизатор Sensa-Trac газовый...»',
          ad_id: 23842591500540110,
          adset_id: 23842591500530110,
          adset_name:
            'Публикация: «Амортизатор Monroe Амортизатор Sensa-Trac газовый...»',
          campaign_name:
            'Публикация: «Амортизатор Monroe Амортизатор Sensa-Trac газовый...»',
          campaign_id: 23842591500440110,
          video_watched_3_s_percent: 0,
          video_watched_15_s_percent: 0,
          video_watched_30_s_percent: 0,
          video_watched_0_s_count: 0,
          video_watched_3_s_count: 0,
          video_watched_15_s_count: 0,
          video_watched_30_s_count: 0,
          video_watched_25_p_count: 0,
          video_watched_50_p_count: 0,
          video_watched_75_p_count: 0,
          video_watched_95_p_count: 0,
          video_watched_100_p_count: 0,
          first_frame_retention: 0,
          video_watched_25_p: 0,
          video_watched_50_p: 0,
          video_watched_75_p: 0,
          video_watched_95_p: 0,
          video_watched_100_p: 0,
          capture_attention: 0,
          hold_attention: 0,
          capture_attention_rate: 0,
          hold_attention_rate: 0,
          engagment: 0,
          engagment_percent: 0,
          click_to_website: 0,
          web_site_ctr: 0,
          link_clicks: 0,
          cpc_outbound_link_click: 0,
          clicks_all: 0,
          ipm: 0,
          cpa: 0,
          cpc_link_click: 0,
          cpm_all: 0,
          cpa_video_view: 0,
          cpa_link_click: 0,
          cost_per_3_s_plays: 0,
          video_retention_100p_3s: 0,
          video_retention_15s_3s: 0,
          thruplay: null,
          thruplay_ctr: 0,
          ctr_all: null,
          thumbstop: 0,
          thumbstop_clickrate: 0,
          atc: 0,
          video_play_curve_actions: [],
        },
        ads: [
          {
            name: 'Публикация: «Амортизатор Monroe Амортизатор Sensa-Trac газовый...»',
            id: '23842591500540110',
          },
        ],
      },
    ],
  },
];

export default TemporaryAdsetsData;
