import { TemporaryReportsDataProps } from './reportsModels';

const TemporaryReportsData: TemporaryReportsDataProps[] = [
  {
    ads: 'SWS | Instant form | GaryVee frant',
    spent: '$45',
    purchaseValue: '$0.00',
    roas: 0.0,
    purchaseRatio: '0.00%',
    purchases: 0,
    thumbstop: '17.83%',
  },
  {
    ads: 'FB | Carousel | Spring Sale',
    spent: '$100',
    purchaseValue: '$250.00',
    roas: 2.5,
    purchaseRatio: '30.00%',
    purchases: 10,
    thumbstop: '12.43%',
  },
  {
    ads: 'Instagram | Video | Summer Collection',
    spent: '$80',
    purchaseValue: '$160.00',
    roas: 2,
    purchaseRatio: '20.00%',
    purchases: 8,
    thumbstop: '18.61%',
  },
  {
    ads: 'Google Ads | Search | Brand Campaign',
    spent: '$200',
    purchaseValue: '$500.00',
    roas: 2.5,
    purchaseRatio: '25.00%',
    purchases: 10,
    thumbstop: '13.34%',
  },
  {
    ads: 'Twitter | Sponsored Tweet | Product Launch',
    spent: '$150',
    purchaseValue: '$300.00',
    roas: 2,
    purchaseRatio: '20.00%',
    purchases: 6,
    thumbstop: '45.67%',
  },
  {
    ads: 'LinkedIn | Sponsored Content | B2B Campaign',
    spent: '$120',
    purchaseValue: '$180.00',
    roas: 1.5,
    purchaseRatio: '15.00%',
    purchases: 6,
    thumbstop: '16.53%',
  },
  {
    ads: 'YouTube | TrueView Ad | Brand Awareness',
    spent: '$180',
    purchaseValue: '$270.00',
    roas: 1.5,
    purchaseRatio: '15.00%',
    purchases: 9,
    thumbstop: '34.2%',
  },
  {
    ads: 'Pinterest | Promoted Pin | Holiday Campaign',
    spent: '$90',
    purchaseValue: '$135.00',
    roas: 1.5,
    purchaseRatio: '15.00%',
    purchases: 6,
    thumbstop: '17.31%',
  },
  {
    ads: 'TikTok | In-Feed Ad | Brand Challenge',
    spent: '$70',
    purchaseValue: '$140.00',
    roas: 2,
    purchaseRatio: '20.00%',
    purchases: 7,
    thumbstop: '5.31%',
  },
  {
    ads: 'Snapchat | Snap Ad | App Install',
    spent: '$110',
    purchaseValue: '$165.00',
    roas: 1.5,
    purchaseRatio: '15.00%',
    purchases: 5,
    thumbstop: '25.46%',
  },
];

export default TemporaryReportsData;
