import { TemporaryReportsDataProps } from './reportsModels';

const TemporaryReportsData: TemporaryReportsDataProps[] = [
  {
    ads: 'SWS | Instant form | GaryVee frant',
    spent: '$45',
    purchaseValue: '17.4%',
    roas: '5.44%',
    purchaseRatio: '13.83%',
    purchases: 0,
    thumbstop: '17.83%',
  },
  {
    ads: 'FB | Carousel | Spring Sale',
    spent: '$100',
    purchaseValue: '12.41%',
    roas: '14.54%',
    purchaseRatio: '30.00%',
    purchases: 10,
    thumbstop: '12.43%',
  },
  {
    ads: 'Instagram | Video | Summer Collection',
    spent: '$80',
    purchaseValue: '22.43%',
    roas: '24.45%',
    purchaseRatio: '98.45%',
    purchases: 8,
    thumbstop: '18.61%',
  },
  {
    ads: 'Google Ads | Search | Brand Campaign',
    spent: '$200',
    purchaseValue: '75.3%',
    roas: '32.41%',
    purchaseRatio: '25.00%',
    purchases: 10,
    thumbstop: '13.34%',
  },
  {
    ads: 'Twitter | Sponsored Tweet | Product Launch',
    spent: '$150',
    purchaseValue: '32.52%',
    roas: '87.56%',
    purchaseRatio: '20.00%',
    purchases: 6,
    thumbstop: '45.67%',
  },
  {
    ads: 'LinkedIn | Sponsored Content | B2B Campaign',
    spent: '$120',
    purchaseValue: '47.5%',
    roas: '43.65%',
    purchaseRatio: '15.00%',
    purchases: 6,
    thumbstop: '16.53%',
  },
  {
    ads: 'YouTube | TrueView Ad | Brand Awareness',
    spent: '$180',
    purchaseValue: '87.21%',
    roas: '34.7%',
    purchaseRatio: '15.00%',
    purchases: 9,
    thumbstop: '34.2%',
  },
  {
    ads: 'Pinterest | Promoted Pin | Holiday Campaign',
    spent: '$90',
    purchaseValue: '23.43%',
    roas: '17.4%',
    purchaseRatio: '15.00%',
    purchases: 6,
    thumbstop: '17.31%',
  },
  {
    ads: 'TikTok | In-Feed Ad | Brand Challenge',
    spent: '$70',
    purchaseValue: '71.5%',
    roas: '65.7%',
    purchaseRatio: '20.00%',
    purchases: 7,
    thumbstop: '5.31%',
  },
  {
    ads: 'Snapchat | Snap Ad | App Install',
    spent: '$110',
    purchaseValue: '43.5%',
    roas: '77.86%',
    purchaseRatio: '15.00%',
    purchases: 5,
    thumbstop: '25.46%',
  },
];

export default TemporaryReportsData;
